### ISSUE TITLE
教程中的写法报错

### ISSUE THREAD

**Issue by stydxm** [tdiant/BukkitDevelopmentNote#19]
我根据[本章节](https://bdn.tdiant.net/#/unit/2-4?id=oncommand)中的写法写了@Override但是IDEA报错
![图片](https://user-images.githubusercontent.com/62790279/117540968-3944b180-b044-11eb-94f4-c7ad0b9b4f78.png)
去掉后就没有问题了
![图片](https://user-images.githubusercontent.com/62790279/117541003-5e392480-b044-11eb-9a45-b94b62b722e5.png)

**Comment by stydxm** [comment]
对不起，是我的问题，谢谢

**Comment by stydxm** [comment]
抱歉我又来了，换新电脑装了新环境之后出现了这个报错，这个报错是什么意思呀（java基础可能不是很好……）
![图片](https://user-images.githubusercontent.com/62790279/127918761-dc30d578-f3aa-4697-ba58-7afc5a2b6711.png)

```java
package cn.vancraft.plugin.vancraftplugin;

import org.bukkit.ChatColor;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.plugin.java.JavaPlugin;

public abstract class Command implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (args.length == 0) {
            sender.sendMessage("插件帮助");
            sender.sendMessage(ChatColor.YELLOW + "/vc reload == 重载插件");
        } else {
            if (args[0].equals("reload")) {
                if (sender.hasPermission("vancraftplugin.reload")) {
                    JavaPlugin.getProvidingPlugin(this.getClass()).reloadConfig();
                    sender.sendMessage(ChatColor.GREEN + "配置已重载");
                } else {
                    sender.sendMessage(ChatColor.RED + "您没有vancraftplugin.reload权限！");
                }
            } else {
                sender.sendMessage("插件帮助");
                sender.sendMessage(ChatColor.YELLOW + "/vc reload == 重载插件");
            }
        }
        return true;
    }
}
```

**Comment by hcrgm** [comment]
> 抱歉我又来了，换新电脑装了新环境之后写齐了四个参数，还是一样的，报错
> ![图片](https://user-images.githubusercontent.com/62790279/127919253-b5904e73-a21b-4d37-a5e3-c20681d53dfe.png)
> 
> 并且出现了这个报错，q请问这个报错是什么意思呀（java基础可能不是很好……）
> ![图片](https://user-images.githubusercontent.com/62790279/127918761-dc30d578-f3aa-4697-ba58-7afc5a2b6711.png)
> 
> ```java
> package cn.vancraft.plugin.vancraftplugin;
> 
> import org.bukkit.ChatColor;
> import org.bukkit.command.CommandExecutor;
> import org.bukkit.command.CommandSender;
> import org.bukkit.plugin.java.JavaPlugin;
> 
> public abstract class Command implements CommandExecutor {
>     @Override
>     public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
>         if (args.length == 0) {
>             sender.sendMessage("插件帮助");
>             sender.sendMessage(ChatColor.YELLOW + "/vc reload == 重载插件");
>         } else {
>             if (args[0].equals("reload")) {
>                 if (sender.hasPermission("vancraftplugin.reload")) {
>                     JavaPlugin.getProvidingPlugin(this.getClass()).reloadConfig();
>                     sender.sendMessage(ChatColor.GREEN + "配置已重载");
>                 } else {
>                     sender.sendMessage(ChatColor.RED + "您没有vancraftplugin.reload权限！");
>                 }
>             } else {
>                 sender.sendMessage("插件帮助");
>                 sender.sendMessage(ChatColor.YELLOW + "/vc reload == 重载插件");
>             }
>         }
>         return true;
>     }
> }
> ```

这个是因为，你的类名`Command`和`org.bukkit.command.Command`有冲突，把你的类名改一下即可

**Comment by stydxm** [comment]
> 
> 
> > 抱歉我又来了，换新电脑装了新环境之后写齐了四个参数，还是一样的，报错
> > ![图片](https://user-images.githubusercontent.com/62790279/127919253-b5904e73-a21b-4d37-a5e3-c20681d53dfe.png)
> > 并且出现了这个报错，q请问这个报错是什么意思呀（java基础可能不是很好……）
> > ![图片](https://user-images.githubusercontent.com/62790279/127918761-dc30d578-f3aa-4697-ba58-7afc5a2b6711.png)
> > ```java
> > package cn.vancraft.plugin.vancraftplugin;
> > 
> > import org.bukkit.ChatColor;
> > import org.bukkit.command.CommandExecutor;
> > import org.bukkit.command.CommandSender;
> > import org.bukkit.plugin.java.JavaPlugin;
> > 
> > public abstract class Command implements CommandExecutor {
> >     @Override
> >     public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
> >         if (args.length == 0) {
> >             sender.sendMessage("插件帮助");
> >             sender.sendMessage(ChatColor.YELLOW + "/vc reload == 重载插件");
> >         } else {
> >             if (args[0].equals("reload")) {
> >                 if (sender.hasPermission("vancraftplugin.reload")) {
> >                     JavaPlugin.getProvidingPlugin(this.getClass()).reloadConfig();
> >                     sender.sendMessage(ChatColor.GREEN + "配置已重载");
> >                 } else {
> >                     sender.sendMessage(ChatColor.RED + "您没有vancraftplugin.reload权限！");
> >                 }
> >             } else {
> >                 sender.sendMessage("插件帮助");
> >                 sender.sendMessage(ChatColor.YELLOW + "/vc reload == 重载插件");
> >             }
> >         }
> >         return true;
> >     }
> > }
> > ```
> 
> 这个是因为，你的类名`Command`和`org.bukkit.command.Command`有冲突，把你的类名改一下即可
> 接口`CommandExecutor`中的`onCommand`方法中cmd参数类型是`org.bukkit.command.Command`

感谢感谢
