### ISSUE TITLE
请求 Contribution guide

### ISSUE THREAD

**Issue by Sakura3r** [tdiant/BukkitDevelopmentNote#5]
请问有无意向编写一份 `CONTRIBUTING.md` 来引导路人为贵项目添砖加瓦？  
章节大纲也可以让路人知道为完成的章节中将要写什么，规范统一的文字风格也许可以让读者理解更加容易。

**Comment by tdiant** [comment]
Thanks for reporting your issue.
We are working on it and it will be published soon.
