### ISSUE TITLE
关于第三节的一些疑惑

### ISSUE THREAD

**Issue by Blank038** [tdiant/BukkitDevelopmentNote#6]
# 对象化的MC -> 玩家(Player)
![image](https://user-images.githubusercontent.com/30598468/75090091-6ec5c200-559a-11ea-9242-c12e7410c458.png)

其他版本我没看过, 在 1.12.2 下, 如果玩家不在线, 应该是 OfflinePlayer 的, 而 getPlayer() 返回的是一个 Player 对象, 通过查看它的代码就可以发现它是先调用 getPlayerExact() 返回的是否为 null, 如果为 null 则进行另一步操作, 这步操作则是从在线玩家中遍历匹配玩家名字, 所以 

> 假如服务器内有abc和ab这两个玩家, 如果你想获取abc的Player对象, 万一abc不在线, 你Bukkit.getPlayer("abc");返回的Player对象, 很有可能是ab的, 而不是abc的.

 这一段话, 我觉得是不对的, 他最后返回的结果都是 Player, 如果玩家离线后, 他肯定是不在的, 再看代码可以发现他是使用 "playerList.a(id);" 这一段来获取的, 而这一段代码到最后的获取点则是一个 Map 集合, 它的键是以UUID形式的, 而他的值则是 NMS 里的 EntityPlayer, 既然是实体, 那下线了就是获取不到的啦。

# 嘛, 玩家不在线, 肯定没办法获取 Player 呀，加油！项目很棒！

**Comment by hcrgm** [comment]
getPlayer(String name)方法确实是模糊搜索, 你可以去查下文档.
不过我看了下, 这里应该说反了, 应该是:  
> Bukkit.getPlayer("ab");返回的Player对象, 很有可能是abc的, 而不是ab的.

毕竟`ab`不可能以`abc`开头嘛  
如果是通过玩家名获取对应玩家对象的话, 是通过nms包中PlayerList类的名为playersByName的map获取的, 不是通过uuid哦.  
还有什么疑问吗?
