### ISSUE TITLE
配置API的序列化和遍历 不符合规范

### ISSUE THREAD

**Issue by tdiant** [tdiant/BukkitDevelopmentNote#7]

**Comment by BakaRinya** [comment]
Thank you for reporting the issue!
Please contact @tdiant ,the fucking author, to ask for fucking correction.

**Comment by BakaRinya** [comment]
We have checked this part and doesn't find any question.
Please point out the mistakes to help us become better.
Thanks for your reporting.

**Comment by BakaRinya** [comment]
We have checked this part and doesn't find any question.
Please point out the mistakes to help us become better.
Thanks for your reporting.

**Comment by hcrgm** [comment]
看你们吵得不可开交的.....这一部分我来重写, 明天下午以PR的形式提交供审阅

**Comment by BakaRinya** [comment]
孩子该打就不能惯着.
